project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"                         # Render all .qmd files
    - "assets/**/*"                  # Include asset folder contents
    - "!content/presentations/**"    # Exclude presentation drafts
    - "!content/documents/**"        # Exclude documents drafts

execute:
  freeze: auto

references:
  - type: r
    title: "Function Reference"
    source: "../man"

website:
  site-url: "https://stat-brain.github.io/cohortED/"
  repo-url: "https://github.com/stat-brain/cohortED"
  title: "cohortED"
  description: "A GitHub repository and reporting toolkit for cohort analysis in education"
  favicon: assets/img/logo_color.png

  page-navigation: true

  navbar:
    title: "cohortED"
    logo: assets/img/logo_grey.png
    logo-alt: "cohortED Package Homepage"
    logo-href: "https://stat-brain.github.io/cohortED/"
    title-href: index.qmd
    search: true
    pinned: true
    foreground: "white"
    left:
      - text: About 
        href: about.qmd
      - text: Getting Started 
        href: getting_started.qmd
      - text: R Package
        menu: 
          - text: Helper Functions
            href: helper_functions.qmd
          - text: Plotting Functions
            href: plotting_functions.qmd
          - text: Analysis Functions
            href: analysis_functions.qmd
          - text: Reporting Functions
            href: reporting_functions.qmd
      - text: Resources
        menu:
          - text: Documents
            href: documents.qmd
          - text: Presentations 
            href: presentations.qmd
          - text: Example Reports
            href: example_reports.qmd
      - text: State Support Tools 
        href: landing.qmd
      - icon: github
        href: https://github.com/stat-brain/cohortED/
        aria-label: "cohortED GitHub Repository"
        target: _blank

  search:
    location: navbar
    type: overlay

  page-footer:
    center:
      - icon: info-square-fill
        href: https://stat-brain.github.io/cohortED/
        aria-label: "About packageSkeleton"
        target: _blank
      - icon: github
        href: https://github.com/stat-brain/cohortED/
        aria-label: "cohortED GitHub Repository"
        target: _blank

  open-graph:
    description: A GitHub repository and reporting toolkit for cohort analysis in education.
    image: assets/img/cohortED_badge.png
    image-alt: cohortED logo
    image-width: 500
    image-height: 500
    locale: en-US

format:
  html:
    theme:
      - cosmo
      - assets/css/website-custom.scss
    css: assets/css/website-styles.css
    toc: true
    number-sections: false
    copy-button: true
    include-after: |
      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,600" rel="stylesheet" type="text/css">
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script type="text/javascript" src="/assets/js/jquery.sticky-kit.min.js"></script>
      <script type="text/javascript" src="/assets/js/scroll.js"></script>
      <script type="text/javascript" src="/assets/js/logo-switch.js"></script>
      <script type="text/javascript" src="/assets/js/custom-anchors.js"></script>
