#' Generate a Narrative Summary of Cohort Persistence Trends
#'
#' @description
#' Creates narrative summaries to accompany cohort persistence tables and heatmaps
#' generated by `analyze_student_cohorts()`. It highlights cohort size, retention,
#' and trends across join years, and optionally flags potential issues or next steps
#' for deeper analysis.
#'
#' This function is designed for use in reporting workflows and returns a list with
#' both an executive summary and a more detailed paragraph. Conditional recommendations
#' are also included as a third element to guide analysts in further exploration.
#'
#' @param summary_table A cleaned summary table from `analyze_student_cohorts()`,
#' typically the `Summary` element of its output. This table must contain columns:
#' `"Cohort"`, `"Join Year"`, `"Year"`, `"Grade"`, `"Number of Students"`,
#' `"Cohort Entry Size"`, and `"Percent Retained"`.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{Executive_Summary}{A one-sentence paragraph suitable for use in brief reports or introductions.}
#'   \item{Detailed_Summary}{A longer paragraph with contextual detail about cohort size and retention.}
#'   \item{Recommendations}{A plain-text list of conditional follow-up steps for analysts.}
#' }
#'
#' @export
#' 

report_cohort_overview <- function(summary_table) {
  # Ensure required columns exist
  required_cols <- c("Cohort", "Join Year", "Cohort Entry Size", "Percent Retained")
  if (!all(required_cols %in% names(summary_table))) {
    stop("Input must be a valid summary table from analyze_student_cohorts().")
  }
  
  # Ensure Join Year is numeric
  summary_table[["Join Year"]] <- as.numeric(summary_table[["Join Year"]])
  entry_years <- unique(summary_table[["Join Year"]])
  
  # Get unique cohorts and entry years
  cohort_labels <- unique(summary_table[["Cohort"]])
  n_cohorts <- length(cohort_labels)
  min_year <- min(entry_years, na.rm = TRUE)
  max_year <- max(entry_years, na.rm = TRUE)
  year_labels <- to_academic_year(sort(entry_years))
  
  # Entry sizes (at join year)
  entry_data <- summary_table[summary_table[["Year"]] == summary_table[["Join Year"]], ]
  entry_sizes <- entry_data[["Cohort Entry Size"]]
  avg_size <- round(mean(entry_sizes, na.rm = TRUE))
  min_size <- min(entry_sizes, na.rm = TRUE)
  max_size <- max(entry_sizes, na.rm = TRUE)
  
  # Final year retention
  final_year_data <- do.call(rbind, lapply(split(summary_table, summary_table[["Cohort"]]), function(df) {
    df[df[["Year"]] == max(df[["Year"]], na.rm = TRUE), ]
  }))
  avg_retained <- round(mean(final_year_data[["Percent Retained"]], na.rm = TRUE), 1)
  
  # Executive summary
  exec <- paste0(
    "This analysis includes ", n_cohorts, " student cohorts spanning academic years ",
    to_academic_year(min_year), " through ", to_academic_year(max_year), 
    ". Average cohort size was about ", avg_size, 
    " students, with approximately ", avg_retained, "% retained through the most recent year."
  )
  
  # Detailed summary
  detail <- paste0(
    "A total of ", n_cohorts, " student cohorts were identified across entry years ", 
    paste(year_labels, collapse = ", "), ". ",
    "Initial cohort sizes ranged from ", min_size, " to ", max_size, 
    " students (average: ", avg_size, "). ",
    "On average, ", avg_retained, "% of students from each cohort remained on track and were still present in the final observed year. ",
    "This information provides context for understanding persistence patterns across cohorts and may help distinguish systemic trends from anomalies in proficiency outcomes."
  )
  
  # Conditional recommendations
  recs <- c()
  
  if (max_size - min_size > 200) {
    recs <- c(recs, "- Consider examining enrollment or mobility patterns to explain wide variation in cohort entry sizes.")
  }
  
  if (avg_retained < 60) {
    recs <- c(recs, "- Cohort retention appears low; consider using `summarize_grade_transitions()` or plotting retention by subgroup.")
  }
  
  if (any(is.na(summary_table[["Percent Retained"]]))) {
    recs <- c(recs, "- Some cohort retention values are missing; check data completeness or filter out partial cohorts.")
  }
  
  # Final output list
  OUT <- list(
    Executive_Summary = exec,
    Detailed_Summary = detail,
    Recommendations = if (length(recs) > 0) paste(recs, collapse = "\n") else "No additional recommendations based on current summary."
  )
  
  invisible(OUT)
}

